# Generated by Django 4.2 on 2024-10-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
                ('ubicacion_geografica', models.CharField(help_text='Formato: Latitud, Longitud', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/fotos_solicitudes/')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('urbanizaciones', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.urbanizaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes', to='home.usuarios')),
            ],
        ),
    ]
