# Generated by Django 4.2 on 2024-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solicitudvecino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudvecino',
            name='usuario',
        ),
        migrations.AddField(
            model_name='solicitudvecino',
            name='codigo_vecino',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
