# Generated by Django 4.2 on 2024-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_solicitudvecino_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvecino',
            name='distrito',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
