# Generated by Django 4.2 on 2024-10-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_solicitudvecino_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ubicacion_geografica', models.CharField(help_text='Formato: Latitud, Longitud', max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('realizado', 'Realizado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('desecho', 'Desecho')], max_length=50)),
                ('codigo_vecino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.solicitudvecino')),
                ('designacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_designacion', to=settings.AUTH_USER_MODEL)),
                ('urbanizaciones', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.urbanizaciones')),
            ],
        ),
    ]
