# Generated by Django 4.2 on 2024-10-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='distrito',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
