# Generated by Django 4.2 on 2024-10-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_solicitudes_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('distrito', models.CharField(max_length=10)),
                ('urbanizacion', models.CharField(max_length=100)),
                ('latitud_longitud', models.CharField(help_text='Formato: Latitud, Longitud', max_length=100)),
                ('tecnico', models.CharField(max_length=50)),
                ('ubicacion_direccion', models.CharField(max_length=100)),
                ('cuadrilla', models.CharField(max_length=100)),
                ('maquinaria', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('concepto', models.CharField(max_length=100)),
                ('volumen', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fotoInicio', models.ImageField(upload_to='fotos_fichas/')),
                ('fotoDesarollo', models.ImageField(upload_to='fotos_fichas/')),
                ('fotoCulminado', models.ImageField(upload_to='fotos_fichas/')),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('proceso', 'En proceso'), ('abandono', 'Abandonado')], max_length=50)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.solicitudes')),
            ],
        ),
    ]
