# Generated by Django 4.2 on 2024-10-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fichaoperativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoCulminado',
            field=models.ImageField(upload_to='media/fotos_fichas/'),
        ),
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoDesarollo',
            field=models.ImageField(upload_to='media/fotos_fichas/'),
        ),
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoInicio',
            field=models.ImageField(upload_to='media/fotos_fichas/'),
        ),
        migrations.AlterField(
            model_name='solicitudvecino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/fotos_solicitudes/'),
        ),
    ]
