# Generated by Django 4.2 on 2024-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_fichaoperativa_fotoculminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoCulminado',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoDesarollo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fichaoperativa',
            name='fotoInicio',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='solicitudvecino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
